name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install a stable toolchain, clippy, for the MCU target
      run: rustup toolchain install stable --no-self-update --profile minimal --component clippy --target thumbv7em-none-eabihf
    - name: Install a stable toolchain with rustfmt
      run: rustup toolchain install stable --no-self-update --profile minimal --component rustfmt
    - name: Check formatting
      run: make fmt
    - name: Build
      run: make build
    - name: Build examples
      run: make build-examples
    - name: Run tests
      run: make test
    - name: Run clippy
      run: make clippy
